### ISSUE TITLE
BOOST_JOIN error with version 1.2.0

### ISSUE THREAD

**Issue by stumbles** [detrout/qt-gstreamer#1]
Using boost-1.57.0 and get this make failure;

[  1%] Automatic moc for target QtGLib
Generating connect.moc
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
AUTOGEN: error: process for /usr/src/qt-gstreamer-1.2.0/qt-gstreamer-oosb/src/QGlib/connect.moc failed:
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"

moc failed...
src/QGlib/CMakeFiles/QtGLib_automoc.dir/build.make:49: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc' failed
make[2]: *** [src/QGlib/CMakeFiles/QtGLib_automoc] Error 1
CMakeFiles/Makefile2:225: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc.dir/all' failed
make[1]: *** [src/QGlib/CMakeFiles/QtGLib_automoc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by detrout** [comment]
It's caused by https://bugreports.qt.io/browse/QTBUG-22829

Something change from boost 1.55 to 1.57 that broke the previous workaround. Can you try with Qt5? Also what platform are you on?

**Comment by stumbles** [comment]
Yep, compiles fine setting QT_QMAKE_EXECUTABLE to the qt5 qmake and QT_VERSION to 5.

Linux (Lunar-Linux; http://www.lunar-linux.org/ ).

**Comment by stumbles** [comment]
Just to make sure all was well with my qt4 install checked to make sure the old bugs about it and boost join were dealt with. They are, our build scripts add; 

sedit "193i pp.macros[\"BOOST_TT_HAS_OPERATOR_HPP_INCLUDED\"];" src/tools/moc/main.cpp &&
sedit "193i pp.macros[\"BOOST_LEXICAL_CAST_INCLUDED\"];" src/tools/moc/main.cpp 

That does fix a similar build problem with avogadro but doesn't help in this case.

**Comment by stumbles** [comment]
Oh and just for geewhiz, here is the output of the make;

+ running "default_pre_build"
+ validating "/usr/src/qt-gstreamer-1.2.0"
+ creating building dir "/usr/src/qt-gstreamer-1.2.0"
+ Removing old source directory first!
+ Unpacking "/var/spool/lunar/qt-gstreamer-1.2.0.tar.xz" in "/usr/src"
+ building "qt-gstreamer" version "1.2.0" in /usr/src/qt-gstreamer-1.2.0
+ CC_EXT="ccache "
+ CXX_EXT="ccache "
+ CC="gcc"
+ CXX="g++"
+ CPP="cpp"
+ CFLAGS=" -O2 -march=x86-64 -pipe"
+ CXXFLAGS=" -O2 -march=x86-64 -pipe"
+ CPPFLAGS=" -D_FORTIFY_SOURCE=2"
+ LDFLAGS=" -s"
+ Enabled wrapper script usage
+ running "default_cmake_build"
+ running "default_cmake_config"
+ MODULE_PREFIX="/usr"
+ running "Out of source build is required; configuring"
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /var/lib/lunar/compilers/gcc
-- Check for working C compiler: /var/lib/lunar/compilers/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Qt4 (min: 4.7)
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.7") 
-- Found Qt4or5: TRUE  found components:  Core Gui Widgets OpenGL Quick1 Test missing components:  Quick2 Qml
-- Boost version: 1.57.0
-- GCC 4.5 or later detected. Enabling C++0x support in QTGSTREAMER_FLAGS.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gstreamer-1.0'
--   found gstreamer-1.0, version 1.4.5
-- checking for module 'gstreamer-base-1.0'
--   found gstreamer-base-1.0, version 1.4.5
-- Found GSTREAMER_BASE_LIBRARY: /usr/lib64/libgstbase-1.0.so
-- Found GSTREAMER_BASE_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Found GStreamer: /usr/lib64/libgstreamer-1.0.so (Required is at least version "1.0.0") 
-- checking for module 'gstreamer-plugins-base-1.0'
--   found gstreamer-plugins-base-1.0, version 1.4.5
-- checking for module 'gstreamer-app-1.0'
--   found gstreamer-app-1.0, version 1.4.5
-- Found GSTREAMER_APP_LIBRARY: /usr/lib64/libgstapp-1.0.so
-- Found GSTREAMER_APP_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-audio-1.0'
--   found gstreamer-audio-1.0, version 1.4.5
-- Found GSTREAMER_AUDIO_LIBRARY: /usr/lib64/libgstaudio-1.0.so
-- Found GSTREAMER_AUDIO_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-video-1.0'
--   found gstreamer-video-1.0, version 1.4.5
-- Found GSTREAMER_VIDEO_LIBRARY: /usr/lib64/libgstvideo-1.0.so
-- Found GSTREAMER_VIDEO_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-pbutils-1.0'
--   found gstreamer-pbutils-1.0, version 1.4.5
-- Found GSTREAMER_PBUTILS_LIBRARY: /usr/lib64/libgstpbutils-1.0.so
-- Found GSTREAMER_PBUTILS_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Found GStreamerPluginsBase: TRUE (Required is at least version "1.0.0") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.42.1
-- Found GLIB2: /usr/lib64/libglib-2.0.so  
-- checking for module 'gobject-2.0'
--   found gobject-2.0, version 2.42.1
-- Found GObject: /usr/include/glib-2.0  
-- Performing Test USE_OPENGLES
-- Performing Test USE_OPENGLES - Failed
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
-- Found DOXYFILE_IN: /usr/src/qt-gstreamer-1.2.0/Doxyfile.in  

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * Qt - Required for building everything
   * QtOpenGL - Required for OpenGL acceleration in qtvideosink and QtGStreamerUi
   * QtQuick1 (QtDeclarative) - Required for building QtQuick1 support
   * Boost - Required for building QtGLib
   * GStreamer - Required to build QtGStreamer
   * GStreamer base library - Used for building the qtvideosink element
   * GStreamer app library - Required to build QtGStreamerUtils
   * GStreamer audio library - Required to build QtGStreamer
   * GStreamer video library - Required to build QtGStreamer
   * GStreamer pbutils library - Used for building the Discoverer API
   * GLib - Required to build QtGLib
   * GObject - Required to build QtGLib
   * OpenGL - Required for OpenGL rendering support in qtvideosink
   * Doxygen - Used to generate the API documentation

-----------------------------------------------------------------------------
-- Congratulations! All external packages have been found.
-----------------------------------------------------------------------------

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SYSCONF_INSTALL_DIR


-- Build files have been written to: /usr/src/qt-gstreamer-1.2.0/qt-gstreamer-oosb
+ running "default_make"
Scanning dependencies of target QtGLib_automoc
[  1%] Automatic moc for target QtGLib
Generating connect.moc
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
AUTOGEN: error: process for /usr/src/qt-gstreamer-1.2.0/qt-gstreamer-oosb/src/QGlib/connect.moc failed:
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"

moc failed...
src/QGlib/CMakeFiles/QtGLib_automoc.dir/build.make:49: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc' failed
make[2]: *** [src/QGlib/CMakeFiles/QtGLib_automoc] Error 1
CMakeFiles/Makefile2:225: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc.dir/all' failed
make[1]: *** [src/QGlib/CMakeFiles/QtGLib_automoc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stumbles** [comment]
+ running "default_pre_build"
+ validating "/usr/src/qt-gstreamer-1.2.0"
+ creating building dir "/usr/src/qt-gstreamer-1.2.0"
+ Removing old source directory first!
+ Unpacking "/var/spool/lunar/qt-gstreamer-1.2.0.tar.xz" in "/usr/src"
+ building "qt-gstreamer" version "1.2.0" in /usr/src/qt-gstreamer-1.2.0
+ CC_EXT="ccache "
+ CXX_EXT="ccache "
+ CC="gcc"
+ CXX="g++"
+ CPP="cpp"
+ CFLAGS=" -O2 -march=x86-64 -pipe"
+ CXXFLAGS=" -O2 -march=x86-64 -pipe"
+ CPPFLAGS=" -D_FORTIFY_SOURCE=2"
+ LDFLAGS=" -s"
+ Enabled wrapper script usage
+ running "default_cmake_build"
+ running "default_cmake_config"
+ MODULE_PREFIX="/usr"
+ running "Out of source build is required; configuring"
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /var/lib/lunar/compilers/gcc
-- Check for working C compiler: /var/lib/lunar/compilers/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Qt4 (min: 4.7)
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.7") 
-- Found Qt4or5: TRUE  found components:  Core Gui Widgets OpenGL Quick1 Test missing components:  Quick2 Qml
-- Boost version: 1.57.0
-- GCC 4.5 or later detected. Enabling C++0x support in QTGSTREAMER_FLAGS.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gstreamer-1.0'
--   found gstreamer-1.0, version 1.4.5
-- checking for module 'gstreamer-base-1.0'
--   found gstreamer-base-1.0, version 1.4.5
-- Found GSTREAMER_BASE_LIBRARY: /usr/lib64/libgstbase-1.0.so
-- Found GSTREAMER_BASE_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Found GStreamer: /usr/lib64/libgstreamer-1.0.so (Required is at least version "1.0.0") 
-- checking for module 'gstreamer-plugins-base-1.0'
--   found gstreamer-plugins-base-1.0, version 1.4.5
-- checking for module 'gstreamer-app-1.0'
--   found gstreamer-app-1.0, version 1.4.5
-- Found GSTREAMER_APP_LIBRARY: /usr/lib64/libgstapp-1.0.so
-- Found GSTREAMER_APP_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-audio-1.0'
--   found gstreamer-audio-1.0, version 1.4.5
-- Found GSTREAMER_AUDIO_LIBRARY: /usr/lib64/libgstaudio-1.0.so
-- Found GSTREAMER_AUDIO_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-video-1.0'
--   found gstreamer-video-1.0, version 1.4.5
-- Found GSTREAMER_VIDEO_LIBRARY: /usr/lib64/libgstvideo-1.0.so
-- Found GSTREAMER_VIDEO_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- checking for module 'gstreamer-pbutils-1.0'
--   found gstreamer-pbutils-1.0, version 1.4.5
-- Found GSTREAMER_PBUTILS_LIBRARY: /usr/lib64/libgstpbutils-1.0.so
-- Found GSTREAMER_PBUTILS_INCLUDE_DIR: /usr/include/gstreamer-1.0
-- Found GStreamerPluginsBase: TRUE (Required is at least version "1.0.0") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.42.1
-- Found GLIB2: /usr/lib64/libglib-2.0.so  
-- checking for module 'gobject-2.0'
--   found gobject-2.0, version 2.42.1
-- Found GObject: /usr/include/glib-2.0  
-- Performing Test USE_OPENGLES
-- Performing Test USE_OPENGLES - Failed
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
-- Found DOXYFILE_IN: /usr/src/qt-gstreamer-1.2.0/Doxyfile.in  

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * Qt - Required for building everything
   * QtOpenGL - Required for OpenGL acceleration in qtvideosink and QtGStreamerUi
   * QtQuick1 (QtDeclarative) - Required for building QtQuick1 support
   * Boost - Required for building QtGLib
   * GStreamer - Required to build QtGStreamer
   * GStreamer base library - Used for building the qtvideosink element
   * GStreamer app library - Required to build QtGStreamerUtils
   * GStreamer audio library - Required to build QtGStreamer
   * GStreamer video library - Required to build QtGStreamer
   * GStreamer pbutils library - Used for building the Discoverer API
   * GLib - Required to build QtGLib
   * GObject - Required to build QtGLib
   * OpenGL - Required for OpenGL rendering support in qtvideosink
   * Doxygen - Used to generate the API documentation

-----------------------------------------------------------------------------
-- Congratulations! All external packages have been found.
-----------------------------------------------------------------------------

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SYSCONF_INSTALL_DIR


-- Build files have been written to: /usr/src/qt-gstreamer-1.2.0/qt-gstreamer-oosb
+ running "default_make"
Scanning dependencies of target QtGLib_automoc
[  1%] Automatic moc for target QtGLib
Generating connect.moc
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
AUTOGEN: error: process for /usr/src/qt-gstreamer-1.2.0/qt-gstreamer-oosb/src/QGlib/connect.moc failed:
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"

moc failed...
src/QGlib/CMakeFiles/QtGLib_automoc.dir/build.make:49: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc' failed
make[2]: *** [src/QGlib/CMakeFiles/QtGLib_automoc] Error 1
CMakeFiles/Makefile2:225: recipe for target 'src/QGlib/CMakeFiles/QtGLib_automoc.dir/all' failed
make[1]: *** [src/QGlib/CMakeFiles/QtGLib_automoc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stumbles** [comment]
Found the problem. The real issue turned out to be boost-1.57. I tried the fix used by the Linux From Scratch folks ; http://www.linuxfromscratch.org/blfs/view/svn/general/boost.html and all is well now.

**Comment by stumbles** [comment]
I'd like to reopen this. Got to thinking the fix used by the lfs folks doesn't seem to be in the right place. I think it should be with those apps using Q_MOC_RUN.

**Comment by stumbles** [comment]
Found a more appropriate patch that was created by https://bugzilla.gnome.org/show_bug.cgi?id=739752. I can now compile the qt4 portion with success.

I now consider this closed.

**Comment by detrout** [comment]
Looks fixed to me too. and more importantly I mirrored the upstream fix from freedesktop here.
