### ISSUE TITLE
Qt-GStreamer not compiling with clang on macosx and with gcc bundled with ndk

### ISSUE THREAD

**Issue by guillaumerybak** [detrout/qt-gstreamer#4]
On macosx with the latest version of XCode, Qt-GStreamer does not compile because of a name clash with the file memory.h and memory. These includes exist inside the stdlib since c++11 and end up being included by clang instead of the ones in src/QGst. The errors went away when I renamed the files "memory.h" and "memory" in the folder src/QGst and in the "#include" statements in several cpp files. 
I don't have the problem with gcc 4.9 and above on osx, but have it with the gcc bundled in the ndk and seems to affect your repository and the one hosted in freedesktop.org

**Comment by rybak-g** [comment]
Sould I make a pull request or can you fix it ?

**Comment by detrout** [comment]
What do you think of the solution in the newly added fix-memory branch? https://github.com/detrout/qt-gstreamer/tree/fix-memory

**Comment by rybak-g** [comment]
Sorry about the delay, seems to do the trick :+1:

**Comment by detrout** [comment]
Thanks for getting back to me. I'll merge it here and try to get the patch into the freedesktop version.
